#ifndef __DEFINSEVALUES__
#define __DEFINSEVALUES__

#define _CRT_SECURE_NO_WARNINGS 
#define TRUE 1
#define FALSE 0
#define FIRST_OPETION_NUMBER 1
#define SECOND_OPETION_NUMBER 2
#define EXIT_OPETION_NUMBER -1
#define MAX_NUMBER_OF_FLOORS 10
#define MAX_NUMBER_OF_ROOMS 100
#define MAX_TO_PRINT_ZERO 10
#define VIEW_BIT 0
#define PORCH_BIT 1
#define KETTLE_BIT 2
#define FREE_WIFI_BIT 3
#define EXTENT_COUCH 4
#define TV_BIT 5
#define AVAILABLE_BIT 6
#define MAX_BIT 7
#define AVAILABLE_ROOM 1
#define MAX_NUMBER_TO_CHECK_ROOM 3
#define MAX_RANDOM_NUMBER 7
#define MIN_RANDOM_NUMBER 0
#define BYTE_LENGTH 8
#define MAX_BIT_INDEX_TO_SET_ZERO 7
#define ARGUMENT_NUMBER 2 
#define FIRST_FLOOR 0
#define FIRST_ROOM 0
#define SECOND_ROOM 1
#define THIRD_ROOM 2
#define ARGUMENT_INDEX 1
#define NAME_TEXT_FOR_RANDOM_NUMBER "encrypt.txt"
#define HOTEL_NAME_SAVE_FILE "hotelDetails.bin"



#endif