void questionOne();
void questionTwo();
void questionThree();
void questionFour();
void questionFive();
void initArray(int* arr,int jumpSize,int number, int size);
void printIndexOfNumbersChar(char str[], char tav);
void sortStringArray(char** strArray);
char* myStrtok(char* str,  char* delimiters);
void printStringArray(char** str,int size);
void printIntMatrix(int *matrix_start, int amount_rows, int amount_columns, int traverse_order);