#ifndef __DEFINESVALUES__
#define __DEFINESVALUES__


#define _CRT_SECURE_NO_WARNINGS 
#define MAX_NUMBER_OF_FLOORS 10
#define MAX_NUMBER_OF_ROOMS 100
#define NUMBER_CRADIT_CARD 13
#define TRUE 1
#define FALSE 0
#define CHECK_IN 1
#define CHECK_OUT 0
#define AVAILABLE 0
#define MIN_VALID_YEAR 2010
#define MAX_VALID_YEAR 2020
#define MIN_VALID_MONTH 1
#define MAX_VALID_MONTH 12
#define MIN_NUMBER_OF_PERSONS 1
#define MAX_NUMBER_OF_PERSONS 4
#define MIN_REGISTERED_BREAKFAST 0
#define MAX_REGISTERED_BREAKFAST 4
#define NUMBER_TO_UPDATE_FIRST_CHAR_STRING 32
#define MAX_ASCII_NUMBER_LOWER_CASE 122
#define MIN_ASCII_NUMBER_LOWER_CASE 97
#define LENGTH_STRING 10
#define MAX_TO_PRINT_ZERO 10



#endif